# Site Settings
title: AMLAAN BHOI
url: 'http://abhoi.github.io'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Amlaan Bhoi
tagline: CS Graduate Student
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Grad student @UIC MSCS '19. Computer vision, statistical data analysis, data science. 
Occasional iOS development (Swift). Former intern @Reliance and @osscube.'

#sidebar links
email: hello@webjeda.com
phone: 012 345 6789
website: blog.webjeda.com #do not add http://
linkedin: alandoe
github: sharu725
twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
